apiVersion: v1
kind: Service
metadata:
  name: "pdf-semantic-indexer"
spec:
  ports:
  - name: http
    port: 80
    targetPort: 6005
{{- if .Values.global.exposeNodePorts }}
    nodePort: 30109
  type: NodePort
{{- end }}
  selector:
    service: pdf-semantic-indexer